### ISSUE TITLE
感谢分享efi，睡眠和关机有点问题

### ISSUE THREAD

**Issue by retornado** [wxjiyc/Lenovo-M710q-QNCT-Hackintosh#2]
非常感谢分享，遇到一点小问题，一是睡眠几秒会自动唤醒硬盘风扇，但是显示器不会唤醒，鼠标键盘可唤醒显示器。二是关机会重启。不知道您是不是也一样的情况，谢谢

**Comment by wxjiyc** [comment]
我没有遇到这样的问题，应该是BIOS差异导致的问题

**Comment by wxjiyc** [comment]
ME关闭后不支持睡眠了
