### ISSUE TITLE
can your Intel Wi-Fi & Bluetooth  support Airdrop?

### ISSUE THREAD

**Issue by JamesLIAOHJ** [wxjiyc/Lenovo-M710q-QNCT-Hackintosh#4]
can your Intel Wi-Fi & Bluetooth  support Airdrop?

**Comment by Jane42070** [comment]
> can your Intel Wi-Fi & Bluetooth support Airdrop?
[itlwm](https://github.com/OpenIntelWireless/itlwm) doesn't support airdrop for now.

**Comment by wxjiyc** [comment]
sorry,unsupported
