### ISSUE TITLE
请教一下DP转HDMI黑屏问题

### ISSUE THREAD

**Issue by ghost** [wxjiyc/Lenovo-M710q-QNCT-Hackintosh#5]
作者你好呀，我的电脑配置和你的差不多：
* QNVH（和QNCT没区别）
* INTEL AC3168 网卡
* WD SN550 固态

其他配置都一样的，但我的显示器只有 HDMI 所以用了 DP 转 HDMI 转换器，在 Windows 下所有功能都正常。但是黑苹果开机的时候，进度条走完一半之后就会无信号。我试了自带的 VGA 也是无信号。

想请教下有办法解决吗？

**Comment by wxjiyc** [comment]
必须购买50元左右的主动式DP转hdmi转接器，被动式的以及vga都不支持

**Comment by ghost** [comment]
@wxjiyc 谢谢老哥，原来如此 😹
