### ISSUE TITLE
m710q + QTJ1

### ISSUE THREAD

**Issue by dheiro** [wxjiyc/Lenovo-M710q-QNCT-Hackintosh#6]
hi, mine is m710q + QTJ1 and running on linux. i want to buy again with QNCT and install hackintosh. is NVME speed with QNCT limited? i see many comment, speed is limited to 800mb

**Comment by sinoyster** [comment]
qtj1  works perfectly

**Comment by wxjiyc** [comment]
same with QNCT,hardware bug
