### ISSUE TITLE
有线网卡有显示，但功能不正常

### ISSUE THREAD

**Issue by sinoyster** [wxjiyc/Lenovo-M710q-QNCT-Hackintosh#7]

**Comment by wxjiyc** [comment]
可能是刷的魔改bios里含有错误的网卡rom

**Comment by sinoyster** [comment]
以太网驱动换成 IntelMausiEthernet.kext 就正常
[RehabMan-IntelMausiEthernet-v2-2018-1031.zip](https://github.com/wxjiyc/Lenovo-M710q-QNCT-Hackintosh/files/9279905/RehabMan-IntelMausiEthernet-v2-2018-1031.zip)
了

**Comment by sinoyster** [comment]
以太网驱动换成这个版本的 IntelMausiEthernet.kext 就正常
[IntelMausiEthernet.kext.zip](https://github.com/wxjiyc/Lenovo-M710q-QNCT-Hackintosh/files/9281298/IntelMausiEthernet.kext.zip)
了
